### ISSUE TITLE
Wrong license in meta.yml

### ISSUE THREAD

**Issue by rolweber** [AnacondaRecipes/ca-certificates-feedstock#2]
The license entry in [recipe/meta.yml](https://github.com/AnacondaRecipes/ca-certificates-feedstock/blob/master/recipe/meta.yaml#L29) says ISC. That is correct for the conda-forge version of this package, which packages certificates from the Python package certifi, which in turn gets its certificates from Mozilla.

This Anaconda version of ca-certificates however gets the certificates from libcurl, and therefore should specify the corresponding license:
https://curl.haxx.se/docs/copyright.html
That change was introduced with PR #1 by @jjhelmus.

**Comment by mingwandroid** [comment]
Do you think SSL certificate are licensable?

For them to be licensable they first need to be copyrightable. Copyright protects only "original works of authorship fixed in any tangible medium of expression.". To my mind, certificates are not works of authorship (or if they are they were authored by the person who created them in the first place), thus they are not copyrightable and therefore also not licensable.

I would replace it with "Unlicensable, uncopyrightable" personally.

**Comment by rolweber** [comment]
That's fine with me as well :-) I just noticed that the license in the metadata doesn't match the origin of the data.

My company has an internal process for clearing OSS packages we use, and ca-certificates has me wondering every time we update it. But for me, it's easier to request a clearance than to discuss with the legal team whether we need one ;-)

**Comment by rolweber** [comment]
Of course, some jurisdictions know copyright on databases, and this is a database of certificates:
https://www.out-law.com/en/topics/branding-and-intellectual-property/copyright/database-rights-the-basics/

**Comment by mingwandroid** [comment]
It's definitely complicated.

I agree we should replace it with the curl one though in the meantime. Maybe we should consult someone for whom `person.IANAL == False` too? I'd like to know to satisfy my own curiosity. It's surprisingly tricky to seach for this subject on the internet.

**Comment by rolweber** [comment]
If you think that is tricky, try searching for the bugtracker for bugzilla... ;-)

**Comment by rolweber** [comment]
@jjhelmus new release, but still the wrong license:
https://github.com/AnacondaRecipes/ca-certificates-feedstock/blob/master/recipe/meta.yaml#L29

**Comment by rolweber** [comment]
I was mistaken. curl doesn't maintain its own CA bundle, they also repackage the certificates from Mozilla:
https://curl.haxx.se/docs/caextract.html

So the ISC license is correct. My apologies for the noise.
