### ISSUE TITLE
No package license file included anywhere in source code, nor installed package

### ISSUE THREAD

**Issue by stevehaertel** [AnacondaRecipes/ca-certificates-feedstock#3]
Environment: Default Anaconda 2019.03 installation

Issue:
meta.yml references an ISC license, but there is no package license included either in the source code, nor installed package location. A default ISC license exists, but it does not include a specific copyright.

https://opensource.org/licenses/ISC

```
about:
    home: https://github.com/conda-forge/ca-certificates-feedstock
    license: ISC
```

**Comment by jjhelmus** [comment]
The latest build of the `ca-certificates` 2019.5.15 has the correct license information (MPL 2.0) and included the license in the package.
